# Generated by Django 2.0.13 on 2019-03-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeData', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencyQuote',
            new_name='QuoteModel',
        ),
    ]
